/**
 * Reads src/data/catalog-content-source.csv (CMS export) and emits
 * src/data/catalog-product-extras.gen.ts — a `Record<QuoteableItemId, ProductExtras>`
 * map merged into QUOTEABLE_ITEMS at runtime.
 *
 * Run: npx tsx scripts/build-catalog-extras.ts
 *
 * The CSV groups rows by (category_slug, product_line_en). For each group we keep:
 *   - countryOfOrigin: first non-empty `Country of origin` (rows for the same
 *     product should agree)
 *   - displayFormats: every non-empty `variation_label_en`, in CSV order, as
 *     authored (we do NOT split on commas — phrases like "5 litr bottle + bulk
 *     (IBC tank)" must stay whole)
 *
 * Catalog product lines whose English name differs from the CMS row are
 * resolved via PRODUCT_LINE_ALIASES below.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { QUOTEABLE_ITEMS, type QuoteableItem } from "../src/lib/catalog";

type CsvRow = Record<string, string>;

function parseCsv(text: string): CsvRow[] {
  const stripped = text.replace(/^\ufeff/, "");
  const records: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < stripped.length; i++) {
    const c = stripped[i]!;
    if (inQuotes) {
      if (c === '"') {
        if (stripped[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
      continue;
    }
    if (c === '"') {
      inQuotes = true;
      continue;
    }
    if (c === ",") {
      row.push(field);
      field = "";
      continue;
    }
    if (c === "\r") continue;
    if (c === "\n") {
      row.push(field);
      records.push(row);
      field = "";
      row = [];
      continue;
    }
    field += c;
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    records.push(row);
  }

  const [header, ...body] = records.filter((r) => r.some((v) => v !== ""));
  if (!header) return [];
  return body.map((cells) => {
    const obj: CsvRow = {};
    header.forEach((key, idx) => {
      obj[key.trim()] = (cells[idx] ?? "").trim();
    });
    return obj;
  });
}

/**
 * CMS product line names that don't match the live catalog. The right-hand
 * value is the English `lineLabel` of the target QuoteableItem. Update here
 * when marketing renames a row in the CSV without changing the catalog.
 */
const PRODUCT_LINE_ALIASES: Record<string, string> = {
  "Soybean Cake (Meal)": "Soybean Cake",
  "Animal Feed": "Feed Grains",
};

function findQuoteableId(
  categorySlug: string,
  productLineEn: string
): string | undefined {
  const target = PRODUCT_LINE_ALIASES[productLineEn] ?? productLineEn;
  const match = QUOTEABLE_ITEMS.find(
    (q) => q.categorySlug === categorySlug && q.lineLabel.en === target
  );
  return match?.id;
}

type Extras = {
  countryOfOrigin?: string;
  displayFormats: string[];
};

function buildExtras(rows: CsvRow[]): Map<string, Extras> {
  const out = new Map<string, Extras>();
  const unmatched: { categorySlug: string; productLineEn: string }[] = [];

  for (const row of rows) {
    const categorySlug = row.category_slug;
    const productLineEn = row.product_line_en;
    if (!categorySlug || !productLineEn) continue;

    const id = findQuoteableId(categorySlug, productLineEn);
    if (!id) {
      unmatched.push({ categorySlug, productLineEn });
      continue;
    }

    const existing = out.get(id) ?? { displayFormats: [] };
    const country = row["Country of origin"];
    if (country && !existing.countryOfOrigin) {
      existing.countryOfOrigin = country;
    }
    const format = row.variation_label_en;
    if (format && !existing.displayFormats.includes(format)) {
      existing.displayFormats.push(format);
    }
    out.set(id, existing);
  }

  if (unmatched.length) {
    console.warn(
      `Warning: ${unmatched.length} CSV row(s) had no matching QuoteableItem:`
    );
    for (const u of unmatched) {
      console.warn(`  - ${u.categorySlug} / ${u.productLineEn}`);
    }
  }

  return out;
}

function reportCoverage(extras: Map<string, Extras>): void {
  const missing: QuoteableItem[] = [];
  for (const item of QUOTEABLE_ITEMS) {
    if (!extras.has(item.id)) missing.push(item);
  }
  if (missing.length) {
    console.warn(
      `Note: ${missing.length} QuoteableItem(s) had no CSV coverage:`
    );
    for (const m of missing) {
      console.warn(`  - ${m.id} (${m.lineLabel.en})`);
    }
  }
}

function tsString(s: string): string {
  return JSON.stringify(s);
}

function emit(extras: Map<string, Extras>): string {
  const lines: string[] = [];
  lines.push(
    "/* AUTO-GENERATED by scripts/build-catalog-extras.ts — do not edit by hand. */"
  );
  lines.push('import type { Localized } from "@/lib/catalog";');
  lines.push("");
  lines.push("export type ProductExtras = {");
  lines.push("  countryOfOrigin?: Localized;");
  lines.push("  displayFormats?: Localized[];");
  lines.push("};");
  lines.push("");
  lines.push(
    "/** Keyed by QuoteableItem.id. French strings mirror English until a FR column lands in the CMS. */"
  );
  lines.push(
    "export const PRODUCT_EXTRAS: Readonly<Record<string, ProductExtras>> = {"
  );

  const ids = [...extras.keys()].sort();
  for (const id of ids) {
    const e = extras.get(id)!;
    const parts: string[] = [];
    if (e.countryOfOrigin) {
      parts.push(
        `    countryOfOrigin: { en: ${tsString(
          e.countryOfOrigin
        )}, fr: ${tsString(e.countryOfOrigin)} },`
      );
    }
    if (e.displayFormats.length) {
      parts.push("    displayFormats: [");
      for (const f of e.displayFormats) {
        parts.push(`      { en: ${tsString(f)}, fr: ${tsString(f)} },`);
      }
      parts.push("    ],");
    }
    if (!parts.length) continue;
    lines.push(`  ${tsString(id)}: {`);
    lines.push(...parts);
    lines.push("  },");
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const cwd = process.cwd();
  const csvPath = join(cwd, "src/data/catalog-content-source.csv");
  const outPath = join(cwd, "src/data/catalog-product-extras.gen.ts");

  const csv = readFileSync(csvPath, "utf8");
  const rows = parseCsv(csv);
  const extras = buildExtras(rows);
  reportCoverage(extras);

  writeFileSync(outPath, emit(extras), "utf8");
  console.log(`Wrote ${outPath} (${extras.size} entries)`);
}

main();
