/* AUTO-GENERATED by scripts/build-catalog-extras.ts — do not edit by hand. */
import type { Localized } from "@/lib/catalog";

export type ProductExtras = {
  countryOfOrigin?: Localized;
  displayFormats?: Localized[];
};

/** Keyed by QuoteableItem.id. French strings mirror English until a FR column lands in the CMS. */
export const PRODUCT_EXTRAS: Readonly<Record<string, ProductExtras>> = {
  "export-ag-commodities-canola-oil": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "16litr, 1000litr", fr: "16litr, 1000litr" },
    ],
  },
  "export-ag-commodities-lentils": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "1kg, 25kg, bulk", fr: "1kg, 25kg, bulk" },
    ],
  },
  "export-ag-commodities-peas": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "1kg, 25kg, bulk", fr: "1kg, 25kg, bulk" },
    ],
  },
  "export-fertilizers-compound-fertilizers-custom-npk-blends": {
    countryOfOrigin: { en: "Canada, Poland, Morocco", fr: "Canada, Poland, Morocco" },
    displayFormats: [
      { en: "50kg, 1t. big bag", fr: "50kg, 1t. big bag" },
    ],
  },
  "export-fertilizers-nitrogen-fertilizers": {
    countryOfOrigin: { en: "Canada, Middle East", fr: "Canada, Middle East" },
    displayFormats: [
      { en: "50kg, 1t. big bag, bulk", fr: "50kg, 1t. big bag, bulk" },
    ],
  },
  "export-fertilizers-phosphate-fertilizers": {
    countryOfOrigin: { en: "Morocco, Middle East", fr: "Morocco, Middle East" },
    displayFormats: [
      { en: "50kg, 1t. big bag, bulk", fr: "50kg, 1t. big bag, bulk" },
    ],
  },
  "export-fertilizers-potash-fertilizers": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "50kg, 1t. - big bag, bulk", fr: "50kg, 1t. - big bag, bulk" },
    ],
  },
  "export-special-crops-hops": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "5kg vaccum packs, 25kg carton box", fr: "5kg vaccum packs, 25kg carton box" },
    ],
  },
  "export-wood-logs": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
  },
  "export-wood-lumber": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "bundled lumber packs", fr: "bundled lumber packs" },
    ],
  },
  "export-wood-wood-pellets": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
    displayFormats: [
      { en: "15-25kg, 1t. - big bag", fr: "15-25kg, 1t. - big bag" },
    ],
  },
  "export-wood-wood-pulp-bskp-bhkp": {
    countryOfOrigin: { en: "Canada", fr: "Canada" },
  },
  "feed-custom-blends-custom-feed-blends": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "50kg, 1 t.", fr: "50kg, 1 t." },
    ],
  },
  "feed-feed-grains-feed-grains": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "50kg, 1 t.", fr: "50kg, 1 t." },
    ],
  },
  "feed-feed-oils-fats-animal-fat-tallow": {
    countryOfOrigin: { en: "Ukraine, Azerbaijan", fr: "Ukraine, Azerbaijan" },
    displayFormats: [
      { en: "1000l", fr: "1000l" },
    ],
  },
  "feed-feed-oils-fats-poultry-fat": {
    countryOfOrigin: { en: "Ukraine, Poland, Azerbaijan", fr: "Ukraine, Poland, Azerbaijan" },
    displayFormats: [
      { en: "1000l", fr: "1000l" },
    ],
  },
  "feed-feed-oils-fats-vegetable-oils": {
    countryOfOrigin: { en: "Ukraine, Canada, Brazil", fr: "Ukraine, Canada, Brazil" },
    displayFormats: [
      { en: "1l, 5l, 20l", fr: "1l, 5l, 20l" },
    ],
  },
  "feed-soybean-cake-soybean-cake": {
    countryOfOrigin: { en: "Ukraine, Brazil", fr: "Ukraine, Brazil" },
    displayFormats: [
      { en: "50kg, 1 t.", fr: "50kg, 1 t." },
    ],
  },
  "feed-sunflower-meal-sunflower-meal-cake": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "50kg, 1 t.", fr: "50kg, 1 t." },
    ],
  },
  "food-canned-canned-tomatoes": {
    countryOfOrigin: { en: "Ukraine, Poland", fr: "Ukraine, Poland" },
    displayFormats: [
      { en: "400g, 720ml-1 litr (glass jars)", fr: "400g, 720ml-1 litr (glass jars)" },
    ],
  },
  "food-canned-pickled-cucumbers": {
    countryOfOrigin: { en: "Ukraine, Poland", fr: "Ukraine, Poland" },
    displayFormats: [
      { en: "720ml-1 litr (glass jars)", fr: "720ml-1 litr (glass jars)" },
    ],
  },
  "food-canned-vegetable-mixes-appetizers-lecho-salads-spreads": {
    countryOfOrigin: { en: "Ukraine, Bulgaria", fr: "Ukraine, Bulgaria" },
    displayFormats: [
      { en: "350g, 500g, 720ml", fr: "350g, 500g, 720ml" },
    ],
  },
  "food-flour-bakery-bakery-products": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
  },
  "food-flour-bakery-rusks-dry-bread": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "250g, 500g", fr: "250g, 500g" },
    ],
  },
  "food-flour-bakery-wheat-flour": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "1 kg", fr: "1 kg" },
    ],
  },
  "food-fresh-fruits-bananas": {
    countryOfOrigin: { en: "Ecuador, Colombia", fr: "Ecuador, Colombia" },
    displayFormats: [
      { en: "18kg - banana box", fr: "18kg - banana box" },
    ],
  },
  "food-fresh-fruits-mandarins-clementines": {
    countryOfOrigin: { en: "Spain, Turkey, Morocco", fr: "Spain, Turkey, Morocco" },
    displayFormats: [
      { en: "10kg - box", fr: "10kg - box" },
    ],
  },
  "food-fresh-fruits-oranges": {
    countryOfOrigin: { en: "Spain, Turkey, Morocco", fr: "Spain, Turkey, Morocco" },
    displayFormats: [
      { en: "15kg - oranges box", fr: "15kg - oranges box" },
    ],
  },
  "food-fresh-fruits-seasonal-fruits-on-request": {
    countryOfOrigin: { en: "Mexico, USA, Costa Rica", fr: "Mexico, USA, Costa Rica" },
    displayFormats: [
      { en: "250g, 500g, 1-3 kg", fr: "250g, 500g, 1-3 kg" },
    ],
  },
  "food-grains-cereals-buckwheat": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "1kg", fr: "1kg" },
    ],
  },
  "food-grains-cereals-other-cereals-on-request": {
    countryOfOrigin: { en: "Ukraine, Poland", fr: "Ukraine, Poland" },
    displayFormats: [
      { en: "500g, 1kg", fr: "500g, 1kg" },
    ],
  },
  "food-grains-cereals-pearl-barley": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "1kg", fr: "1kg" },
    ],
  },
  "food-honey-jams-nuts-fruit-jams-preserves": {
    countryOfOrigin: { en: "Ukraine, Poland", fr: "Ukraine, Poland" },
    displayFormats: [
      { en: "350g, 500g", fr: "350g, 500g" },
    ],
  },
  "food-honey-jams-nuts-natural-honey": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "250g, 500g", fr: "250g, 500g" },
    ],
  },
  "food-honey-jams-nuts-nuts-almonds-hazelnuts-mixes": {
    countryOfOrigin: { en: "Ukraine, Turkey, Georgia", fr: "Ukraine, Turkey, Georgia" },
    displayFormats: [
      { en: "200g, 500g", fr: "200g, 500g" },
    ],
  },
  "food-juices-drinks-carbonated-drinks": {
    countryOfOrigin: { en: "Poland", fr: "Poland" },
    displayFormats: [
      { en: "330ml, 500ml", fr: "330ml, 500ml" },
    ],
  },
  "food-juices-drinks-fruit-juices": {
    countryOfOrigin: { en: "Ukraine, Poland, Bulgaria", fr: "Ukraine, Poland, Bulgaria" },
    displayFormats: [
      { en: "1litr, 2 litr", fr: "1litr, 2 litr" },
    ],
  },
  "food-juices-drinks-protein-drinks": {
    countryOfOrigin: { en: "Poland, USA", fr: "Poland, USA" },
    displayFormats: [
      { en: "330ml, 500ml", fr: "330ml, 500ml" },
    ],
  },
  "food-juices-drinks-vitamin-functional-drinks": {
    countryOfOrigin: { en: "Poland", fr: "Poland" },
    displayFormats: [
      { en: "330ml, 500ml", fr: "330ml, 500ml" },
    ],
  },
  "food-oils-olive-oil": {
    countryOfOrigin: { en: "Greece", fr: "Greece" },
    displayFormats: [
      { en: "1 litr", fr: "1 litr" },
    ],
  },
  "food-oils-soybean-oil": {
    countryOfOrigin: { en: "Ukraine, Brazil", fr: "Ukraine, Brazil" },
    displayFormats: [
      { en: "5 litr bottle + bulk (IBC tank)", fr: "5 litr bottle + bulk (IBC tank)" },
    ],
  },
  "food-oils-sunflower-oil": {
    countryOfOrigin: { en: "Ukraine", fr: "Ukraine" },
    displayFormats: [
      { en: "1 litr", fr: "1 litr" },
    ],
  },
  "food-rice-rice": {
    countryOfOrigin: { en: "Bangladesh, Thailand", fr: "Bangladesh, Thailand" },
    displayFormats: [
      { en: "1kg, 5kg", fr: "1kg, 5kg" },
    ],
  },
  "food-salt": {
    countryOfOrigin: { en: "Brazil", fr: "Brazil" },
    displayFormats: [
      { en: "1 kg", fr: "1 kg" },
      { en: "25 kg", fr: "25 kg" },
    ],
  },
  "food-sugar-sugar": {
    countryOfOrigin: { en: "Poland, Ukraine", fr: "Poland, Ukraine" },
    displayFormats: [
      { en: "1 kg", fr: "1 kg" },
    ],
  },
};
